# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'simple-bill-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire'
  pod 'KRProgressHUD'
  pod 'ReactiveCocoa', '~> 8.0'
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'

  # Pods for simple-bill-swift

  target 'simple-bill-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'simple-bill-swiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
